name = "DiffEqDiffTools"
uuid = "01453d9d-ee7c-5054-8395-0335cb756afa"
version = "1.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
BlockBandedMatrices = "ffab5731-97b5-5995-9138-79e8c1846df0"

[compat]
julia = "1"
ArrayInterface = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
